### PR TITLE
armbian fix

### PR DESCRIPTION
**Pull request by luxflow**
- remove NetworkManager
- disable armbian first-login adduser
- set DHCP as default

### CODE REVIEW

**Comment by guysoft** [comment]
Hey, great work!
Question:  
How come ``BASE_ROOT_PARTITION=2``? 
Last time I checked armbian had a single partition for both boot and root.
Against what image are you testing?

**Comment by luxflow** [comment]
Armbian by default, only have a single partition by default (ext4 for both /boot, /root)

but you can build with two partition by changing option (fat for /boot, ext4 for /root)
check out `how to build "fat" bootfs armbian image?`
https://github.com/luxflow/CustomPiOS/releases/tag/buster

**Comment by guysoft** [comment]
I rather have the variant build with the publicly available Armbian images, since this would require you to build a whole image just to use CustomPiOS which kinda misses the point of using it in the first place.
CustomPiOS should be able to handle both but default to the default settings so when you start you get the minimal of clashes. And you can set your special settings in your own distro config file.

Should I fix this or you?

**Comment by guysoft** [comment]
Thanks for contributing!

**Pull request merged**
