### PR TITLE
fixes for Armbian

### PR DESCRIPTION
**Pull request by huelvayork**
keep original /etc/network/interfaces 
don't add i2c group to user pi (i2c group doesn't exist in armbian)

### CODE REVIEW

**Comment by huelvayork** [comment]
With these changes the image builds, boots and has network access, but octoprint still won't work (need to fix the "systemctl disable lightdm" issue in OctoPi/src/modules/octopi/start_chroot_script )

**Comment by guysoft** [comment]
Hey, so I've also been working on this. There is a difference between Armbian Jessie and Armbian Ubuntu. So i2c, for example exists in Jessie and not in Ubuntu. I'll push something more flexible soon.

**Comment by huelvayork** [comment]
I'm closing the PR since you'll address the i2c issue, and the interfaces patch may break compatibility with octopi-network.txt

**Comment by guysoft** [comment]
I rather keep it open until I commit my changes

**Comment by guysoft** [comment]
@huelvayork Did you manage to get the wifi working on ubuntu? I am not sure if its my dongle, but it didn't seem to work here,

**Comment by huelvayork** [comment]
Dongle? I was using Orange Pi Zero with its onboard wifi.
(Only the stable, "Legacy kernel" version supports it)

**Comment by guysoft** [comment]
I only have a hummingboard to test

**Comment by huelvayork** [comment]
I can test with orange pi zero and a dongle. Will try this weekend.

**Comment by ChrisP-Git** [comment]
Hi, I'm trying to build OctoPi with armbian for odroid c1 (The headless Jessie version) but still get the issue with the i2c group. What is the actual status, did you push the fixes ?

**Comment by guysoft** [comment]
@ChrisP-git I did, this is the commit: https://github.com/guysoft/CustomPiOS/commit/cae9546a81629cf9558a74dc91775a894583bb6b

Make sure you pulled.
Also, if you still get the error share the output of build.log

**Comment by ChrisP-Git** [comment]
Thanks for the hint, I believed I was up to date, but doing a git pull on both OctoPi and CustomPIOS fixed the issue. I had then another strange issue and created a new issue on it.
Thanks again, this is awesome.

**Pull request closed without merging**
