### PR TITLE
Add support for network manager and wpa-supplicant in network module

### LINKED ISSUE #219: wpa_supplicant autoconfigure removed in bookworm but not replaced with other mechanism, breaking network module
In bookworm Raspberry Foundation/Ltd has removed wpa-suppilcant and switched to NetworkManger
In the network module we add a way to headless configure wpa-supplicant.

This is where its done in the network module:
https://github.com/guysoft/CustomPiOS/blob/devel/src/modules/network/start_chroot_script#L36

This is the issue on Rpi:
https://github.com/raspberrypi/bookworm-feedback/issues/72

This  is a related issue in FullPageOS:
https://github.com/guysoft/FullPageOS/issues/570

What I think should be done is perhaps have an if statement depending on the distribution version, and use [the solution here for bookworm](https://github.com/raspberrypi/bookworm-feedback/issues/72#issuecomment-1848778447), and perhaps add a symlnink from the old file. Open to other suggestions.
Might take me time to implement because I am busy theses days.

### PR DESCRIPTION
**Pull request by guysoft**
Creates a file wifi.nmconnection in the boot folder if used, and lets you set up a NetworkManager connection.

I kept it low level so people can put more exotic settings in the file, for example static ips, multiple ips. etc.

Internally it copies the file each boot - would be happy to get a better solution than that. but the permissions got to be 600.

Fixes #219
Related:
https://github.com/raspberrypi/bookworm-feedback/issues/72

### CODE REVIEW

**Comment by guysoft** [comment]
Asked here NetworkManager if we need to generate a uuid or not:
https://lists.freedesktop.org/archives/networkmanager/2024-August/000333.html

**Comment by ingojaeckel** [comment]
Thanks for putting this together! I am testing this in this repo: https://github.com/ingojaeckel/go-raspberry-pi-timelapse/releases/tag/0.5.0

Thanks to your branch, I was able to get my wifi hotspot working again on boot on a RPI Zero W 1.1 on the latest raspios lite (debian 12 bookworm). Only "changes" I needed was
* provide my own `wifi.nmconnection` file via `/boot/firmware/wifi.nmconnection` ([here](https://github.com/ingojaeckel/go-raspberry-pi-timelapse/blob/main/timelapsepi/src/modules/timelapsepi/filesystem/boot/firmware/wifi.nmconnection))
* to speed up boot, add `systemctl disable NetworkManager-wait-online.service` ([here](https://github.com/ingojaeckel/go-raspberry-pi-timelapse/commit/d462ed365f5122796f92cf9535d876cb675af428))

**Review by ingojaeckel — APPROVED** [review]

**Comment by guysoft** [comment]
@ingojaeckel Thats cool!
Your comment also comes in a good time because we are just at a crossroad to decide if this PR will get in or this one:
https://github.com/guysoft/CustomPiOS/pull/230
I was not sure if to keep this, but if you are using it then it makes sense to merge and have all 3 options.

Also Cool! - do you want to add https://github.com/ingojaeckel/go-raspberry-pi-timelapse/tree/main/timelapsepi to the README of CustomPiOS? You can PR to this section:
https://github.com/guysoft/CustomPiOS?tab=readme-ov-file#list-of-distributions-using-custompios

**Comment by guysoft** [comment]
I am merging this, we also have a work in progress to add a new headless_nm module that would become the default option. I am merging this so CustomPiOS v1 has some option to configure network manager.

**Pull request merged**
