### PR TITLE
Add ssh key functionality to gitclone.

### PR DESCRIPTION
**Pull request by amrsoll**
Allows to clone private repositories using an ssh key.

In the case of automation, you can have an ssh key as a secret, write it to a file in `module/my_module/filesystem/` or `variant/my_variant/filesystem/` and reference the path to that key in your build script.

### CODE REVIEW

**Comment by guysoft** [comment]
I think the if should be 
```
   if [ "$ssh_key" !=  "" ]
```

And not
```
   if [ -n "$ssh_key" ]
```

Based on writing this: 
https://github.com/guysoft/CustomPiOS/blame/devel/src/common.sh#L110

But didn't test.

**Comment by amrsoll** [comment]
Wow thank you for correcting the typo hahaha :sweat_smile: 

I don't understand the recommendation, is it for readability or correctness?

**Comment by guysoft** [comment]
correctness. If it works it works, and you can change the other one too :)
``-n`` is better.

**Comment by amrsoll** [comment]
Yeah well turns out the `-i`  ain't quite correct with git clone (expected it to be the same as the `ssh` command for some reason lol) - testing a different thing now

**Comment by amrsoll** [comment]
So the correct way to do this is to add `--config core.sshCommand="ssh -i path/to/id_rsa"` to the git clon parameters, but shellscripting being what it is, it is soo hacky to make it work with the quotations `"` + there is also a problem with confirming the fingerprint from the other server.

The workaround is obviously to create the `~/.ssh/known_hosts` file but it's even more hacky than I would like it to be.

**Comment by guysoft** [comment]
You have uncommented code committed there:
https://github.com/guysoft/CustomPiOS/pull/112/files/31ecbaa4977d70058217d674b37851eebdbe7a95..aa4e88b704798e3306bab0680800e6b2857e7027#diff-237c21469b21016651ddcc1945c8cb58e320139ec48ffdb81f991edcb795b08aR109

**Comment by amrsoll** [comment]
Yeah I'm sorry it's been a bit of a mess trying to figure out how to make this as clean as possible, still struggling with that and the github secrets.
The option `--config core.sshCommand=\"ssh -i $key\"` does not want to be parsed properly if I put it in a variable first (yay shellscripting) + It still requires to add the relevant `known_hosts` so trying to make something cleaner instead such as cloning the repo into `path/filesystem` through the actions/checkout with an access token.

Perhaps this feature is not worth pursuing.

**Comment by amrsoll** [comment]
In the end I went with `actions/checkout` even if it has it's own issues. (see [build.yml]).

@guysoft Are you interested in this feature or not? Feel free to close if not.

[build.yml]: https://github.com/mrbeam/BeamOS/blob/mrbeam/.github/workflows/build.yml

**Comment by guysoft** [comment]
@amrsoll I personally don't need it. But it might be useful to others. Don't feel obligated to develop it if you are not planning to use it.   :)

You might want to take a loo at what @jeffeb3 is doing at https://github.com/jeffeb3/v1pi
Was talked at #28

He also solved this similar issue using submodules.

I would have loved to have some kind of module repository system.
Something like pip that you can give urls or a name that would pull from a standard repo.
But its not something I have the time for now.

**Comment by amrsoll** [comment]
Thank you! Yep that way of designing the repo makes complete sense as well :)

**Pull request closed without merging**
