### PR TITLE
Fix disabling cockpit socket

### PR DESCRIPTION
**Pull request by asdf1nit**

### CODE REVIEW

**Comment by guysoft** [comment]
Hey, it looks wrong, a module can only import settings with its prefix. so your configu variables should start with COCKPIT_INSTALL.
But you have ``if [ "$DISABLE_COCKPIT_SOCKET" == "yes" ]; then``

**Comment by guysoft** [comment]
Apparently this was not documented, added docs here:
https://github.com/guysoft/CustomPiOS/wiki/Modules#variable-names-in-the-config-file-of-a-module

**Comment by asdf1nit** [comment]
I thought something wasn't right. I was having to export all of the variables to get them to work.

> `
But you have `if [ "$DISABLE_COCKPIT_SOCKET" == "yes" ]; then`
`
This is actually correct for this line as it's a local script that is installed not run in the chroot

Latest commit fixes the variables in the config file and the chroot script.

**Comment by guysoft** [comment]
Ok, ready to pull?

**Comment by asdf1nit** [comment]
Yes this is ready.

**Pull request merged**
