### PR TITLE
WIP: XZ Image Handling + Removed Pi User

### PR DESCRIPTION
**Pull request by pablosproject**
This fixes new changes in new Raspberry images. In detail:

- Uses `xz` extension for image detection and automatic download
- Fixed Qemu scripts
- Add a new module for create a default user

@guysoft I also edited the wiki with the new default user module, let me know if you are happy with it.

### CODE REVIEW

**Comment by guysoft** [comment]
Hey, looks good! There is some indentation that needs fixing.

**Comment by pablosproject** [comment]
I am looking into the impact of the `default-user`. We already have `BASE_USER` and `BASE_USER_ADD` in the `base` module. It also does minor things using the `BASE_USER` variable (creates python configs, etc).

So in my tests, I ran the `base` module and the new `default-user` module, and everything worked, but I am not sure this is correct.
I think that we can just remove the `default-user` module and use the default `BASE_USER`, forcing the default `BASE_USER_ADD` to true. This is because the `base` module needs a user set up to work correctly. 
What do you think?

**Comment by guysoft** [comment]
Ok, looking in to it more I think 
1. the base module should handle the default user
2. the service ``userconf.service`` manages all the changes of user naming, perhaps we could just disable it.

**Comment by guysoft** [comment]
Hey, so I merged the XZ section of this PR. but not the last part that deals with the default user, that needs changing.

**Comment by pablosproject** [comment]
Ok, I am out of the office until tomorrow, then I will find a solution for the default user handling in the base module.

**Comment by pablosproject** [comment]
I tried reconciling both modules but had no luck, so here's what I'm doing:

- We'll keep the `base` module and remove the `default-user` module
- We'll leverage the `BASE_ADD_USER` variable (unused at the moment) to force user creation. It'll be set to `true` by default.
- The base module will create the user and the user folder as the first thing, as other functions and modules depend on having a user set up.

I'll explain in the documentation of the base module this new change and we'll force that. 
In case someone wants to run the raspberry wizard to create the user, `BASE_ADD_USER` needs to be set to `false`, and some functions (like git clone) will not work during the build (but the user will know that as he prompted for not creating a new user).

Will finalize and test as soon as I can this change.

**Comment by guysoft** [comment]
Take a look at this branch:
https://github.com/guysoft/CustomPiOS/tree/default-user

ill merge that once we fix the default user issue

**Comment by pablosproject** [comment]
Ok, fine then.

**Comment by guysoft** [comment]
Hey, just wondering if there anything I can help with to get this merged?

**Comment by pablosproject** [comment]
Hi! Let me get my head around this because I forgot what I did. From what I recall just some part from this were merged:
- c50d74bcef65b220f9801a7d27f9e2eb1ff6e73c
- e88ec0a88f6bffb6cd938d6683f44283aa8adbab
- fbed8fc97d21c716b62041d27838a05ec5ddeb5a
- 47fc3fd88e81ff211b71a764f80eb8f97da29934

The thing related to the default user was solved in another commit. Is that correct?

**Comment by pablosproject** [comment]
Agree, thanks for checking

**Pull request closed without merging**
