### PR TITLE
Admin toolkit

### PR DESCRIPTION
**Pull request by asdf1nit**
This module does a few things that most admins will want to configure before deploying pi's in their environments.

### CODE REVIEW

**Comment by guysoft** [comment]
Apparently this was not documented, added docs here:
https://github.com/guysoft/CustomPiOS/wiki/Modules#variable-names-in-the-config-file-of-a-module

**Comment by asdf1nit** [comment]
> Apparently this was not documented, added docs here:
> https://github.com/guysoft/CustomPiOS/wiki/Modules#variable-names-in-the-config-file-of-a-module

Fixed

**Comment by guysoft** [comment]
Ok, is this ready to be pulled? Or should I wait?

Also it might be word writing here some explanation what this is, and I will add it to the module docs (or directly in the wik once pulled):
https://github.com/guysoft/CustomPiOS/wiki/Modules#list-of-standard-library-modules

**Comment by asdf1nit** [comment]
This is ready.

The explanation from the config file should do fine for the wiki. There is explanation on each setting as well.

**Comment by asdf1nit** [comment]
From the config


admin-toolkit helps to harden your pi, install other packages easily, and add files out of the box.
Some things require a user to be added and others dont. Some things are indended to be used with FullPageOS and the scripts that come with it, but there are uses outside of that, if you edit a bit of code.
This has only been used with FullPageOS, and Raspbian Buster on a pi3/4

**Pull request merged**
