### PR TITLE
add podman module

### PR DESCRIPTION
**Pull request by docgalaxyblock**
I like to share my progress adding a podman module.

It is not final - feel free to suggest changes.

🤗

WIP - Draft

### CODE REVIEW

**Comment by guysoft** [comment]
Cool, update when its ready :)

Also, it might be worth adding in the wiki some explanation about podman, I would love to understand myself how is it different than other container management tools such as docker-compose

https://github.com/guysoft/CustomPiOS/wiki/Modules#list-of-standard-library-modules

**Comment by docgalaxyblock** [comment]
No
It looks like I have messed something up while I relocated all my cloned git stuff to my nas 😅

**Comment by guysoft** [comment]
Ok, if you have a module to PR you are welcome to do so :)
Hope you didn't loose too much data.

**Comment by docgalaxyblock** [comment]
Since we use podman at OpenMowerOS I probably lost nothing 😉
But that version has no distrochecks currently...

I need to find time to learn bash scripting until I can revisit this PR
I will force push what we have at OpenMowerOS soon:tm: so I can reopen this again

**Comment by guysoft** [comment]
Ok, cool, you can also add OpenMowerOS here if it has a working build:
https://github.com/guysoft/CustomPiOS#list-of-distributions-using-custompios

**Pull request closed without merging**
